/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/birds/birds.glb
Author: Vladislav Laryushin (https://sketchfab.com/Zorg741)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/birds-b2c32bd4b78747e5b061c8348128e205
Title: Birds
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Birds(props) {
  const { nodes, materials } = useGLTF("./models/birds/birds.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/birds/birds.glb");
