/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/book/book.glb
Author: Arnau Rocher Alcayde (https://sketchfab.com/ArnauRocherAlcayde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-b2d30398ba3741da9f9aef2319ee2b8b
Title: Book
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Book(props) {
  const { nodes, materials } = useGLTF("./models/book/book.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={[6, 9, 1.5]}>
          <mesh
            geometry={nodes.Book_MAT_Book_0.geometry}
            material={materials.MAT_Book}
          />
          <mesh
            geometry={nodes.Book_MAT_Paper_0.geometry}
            material={materials.MAT_Paper}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/book/book.glb");
