/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/car/cyberpunk_car.glb
Author: 4d_Bob (https://sketchfab.com/3d_Bob)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-car-b4301ff99d214d16a7a43708a5866bf0
Title: Cyberpunk car
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Flower(props) {
  const { nodes, materials } = useGLTF("./models/flower/flower.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Plane002_Flowerpot_0.geometry}
          material={materials.Flowerpot}
          position={[74.25, 409.09, -120.37]}
          rotation={[0.27, 1.23, -0.45]}
          scale={297.93}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/flower/flower.glb");
