/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/health/health.glb
Author: Kevin Saucedo (https://sketchfab.com/ksaucedo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/health-station-b7a95e70fc7848f6bdca97b4f4ad23a7
Title: Health Station
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Health(props) {
  const { nodes, materials } = useGLTF("./models/health/health.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.lambert4SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.lambert4SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/health/health.glb");
