/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/paperBird/paperBird.glb
Author: Durk (https://sketchfab.com/durk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/papercraft-birds-d76fd20c3279499cac6a5db483f4feeb
Title: Papercraft Birds
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PaperBird(props) {
  const { nodes, materials } = useGLTF("./models/paperBird/paperBird.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.23}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.birds}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.birds}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/paperBird/paperBird.glb");
