/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/weapon/weapon.glb
Author: tuomaspaul (https://sketchfab.com/tuomaspaul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soulsucker-weaponcraft-6b27a5a86dad4d13a6ff02ab5a1dcbce
Title: Soulsucker - Weaponcraft
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Weapon(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/weapon/weapon.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.57, 0, 0]} scale={4.07}>
          <group
            name="274c16d753f840328866884786ec81c9fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="geo_sword" position={[0.59, 35.22, 1.07]}>
                  <group name="sword_piece" position={[-0.59, -0.24, -1.07]}>
                    <group name="sword_piece_7" position={[0, -0.25, 0]}>
                      <mesh
                        name="sword_piece_7_M_Sword_0"
                        geometry={nodes.sword_piece_7_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_8" position={[0, -0.17, 0]}>
                      <mesh
                        name="sword_piece_8_M_Sword_0"
                        geometry={nodes.sword_piece_8_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_9" position={[0, -0.2, 0]}>
                      <mesh
                        name="sword_piece_9_M_Sword_0"
                        geometry={nodes.sword_piece_9_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_1" position={[0, -0.02, 0]}>
                      <mesh
                        name="sword_piece_1_M_Sword_0"
                        geometry={nodes.sword_piece_1_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_2">
                      <mesh
                        name="sword_piece_2_M_Sword_0"
                        geometry={nodes.sword_piece_2_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_3" position={[0, -0.04, 0]}>
                      <mesh
                        name="sword_piece_3_M_Sword_0"
                        geometry={nodes.sword_piece_3_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_4">
                      <mesh
                        name="sword_piece_4_M_Sword_0"
                        geometry={nodes.sword_piece_4_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_5">
                      <mesh
                        name="sword_piece_5_M_Sword_0"
                        geometry={nodes.sword_piece_5_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                    <group name="sword_piece_6">
                      <mesh
                        name="sword_piece_6_M_Sword_0"
                        geometry={nodes.sword_piece_6_M_Sword_0.geometry}
                        material={materials.M_Sword}
                      />
                    </group>
                  </group>
                  <group name="sword_main" position={[-0.59, -0.19, -1.07]}>
                    <mesh
                      name="sword_main_M_Sword_0"
                      geometry={nodes.sword_main_M_Sword_0.geometry}
                      material={materials.M_Sword}
                    />
                    <mesh
                      name="sword_main_M_Emissive_0"
                      geometry={nodes.sword_main_M_Emissive_0.geometry}
                      material={materials.M_Emissive}
                    />
                  </group>
                </group>
                <group name="vfx_circle" scale={0.38}>
                  <mesh
                    name="vfx_circle_M_VFX2_0"
                    geometry={nodes.vfx_circle_M_VFX2_0.geometry}
                    material={materials.M_VFX2}
                  />
                </group>
                <group
                  name="vfx_circle1"
                  rotation={[-Math.PI, -1.1, -Math.PI]}
                  scale={[0.48, 0.89, 0.48]}
                >
                  <mesh
                    name="vfx_circle1_M_VFX2_0"
                    geometry={nodes.vfx_circle1_M_VFX2_0.geometry}
                    material={materials.M_VFX2}
                  />
                </group>
                <group name="left" position={[-1000.1, 11.34, 3.26]}>
                  <group name="Object_5" />
                </group>
                <group
                  name="back"
                  position={[-0.93, 6.24, -1000.11]}
                  rotation={[0, -Math.PI / 2, 0]}
                >
                  <group name="Object_7" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/weapon/weapon.glb");
